### ISSUE TITLE
Navigation deprecated

### ISSUE THREAD

**Issue by prateekvarma** [mmuehlberger/tutsplus-social-react-native#4]
Hello,
I'm doing the tutsplus course right now, and i found the navigation component has been deprecated since quite a while now.
I'll appreciate of you could update this part of the code with the latest - ReactNavigation?

**Comment by mmuehlberger** [comment]
Hi! We are aware of the deprecations in the project, and are currently in the process of updating the whole course to be more current, because a lot has changed since we produced it.

I'm also going to use React Navigation to handle navigation there. While I'm not in charge of releasing the course, you should expect the new version within the next month or two. I'm sorry for the inconvenience.
